project:
  type: website
  output-dir: docs

website:
  title: "fblog"
  google-analytics: "G-YJEV4P7Y2S"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css



